// Base de dados local de exercicios
export const exercicios = {
  // PEITO
  "supino-retro-barra": { nome: "Supino Reto com Barra", grupo: "Peito", series: "3x12", descricao: "Exercicio basico para peitoral maior. Deite no banco reto, segure a barra com pegada media, desca ate o peito e empurre.", comoExecutar: "Deite com os pes no chao, segure a barra com pegada um pouco mais larga que os ombros, desca controlando ate tocar levemente o peito, empurre de volta.", cuidados: "Nao arqueie excessivamente a lombar, nao trave os cotovelos no topo, mantenha as escapulas retraidas.", video: "https://www.youtube.com/watch?v=rT7DgCr-3pg" },
  "supino-retro-halteres": { nome: "Supino Reto com Halteres", grupo: "Peito", series: "3x12", descricao: "Variacao com halteres do supino reto, maior amplitude e ativacao.", comoExecutar: "Deite no banco reto, segure halteres na largura dos ombros, desca ate o nivel do peito e suba.", cuidados: "Controle a descida, nao deixe os cotovelos abrirem demais.", video: "https://www.youtube.com/watch?v=VmB1G1K7v9M" },
  "supino-inclinado-barra": { nome: "Supino Inclinado com Barra", grupo: "Peito", series: "3x12", descricao: "Foca na porcao superior do peitoral. Banco a 30-45 graus.", comoExecutar: "Ajuste o banco a 30 graus, segure a barra, desca ate a parte superior do peito e empurre.", cuidados: "Nao exagere na inclinacao, mantenha contato com o banco.", video: "https://www.youtube.com/watch?v=8iPEnn-ltC8" },
  "supino-inclinado-halteres": { nome: "Supino Inclinado com Halteres", grupo: "Peito", series: "3x12", descricao: "Supino inclinado com halteres para melhor amplitude.", comoExecutar: "Banco a 30-45 graus, desca os halteres controlando e suba com forca.", cuidados: "Mantenha os pes firmes no chao, controle o movimento.", video: "https://www.youtube.com/watch?v=8iPEnn-ltC8" },
  "crucifixo-retro": { nome: "Crucifixo Reto", grupo: "Peito", series: "3x12", descricao: "Isolamento do peitoral com abertura lateral.", comoExecutar: "Deite no banco reto com halteres, abra os bracos lateralmente em arco e volte ao centro.", cuidados: "Leve flexao nos cotovelos, nao desca alem da linha dos ombros.", video: "https://www.youtube.com/watch?v=eozdVDA78K0" },
  "peck-deck": { nome: "Peck Deck (Voador)", grupo: "Peito", series: "3x12", descricao: "Maquina para isolamento do peitoral com movimento de abertura/fechamento.", comoExecutar: "Sente com as costas apoiadas, segure as alcas e junte os bracos a frente.", cuidados: "Nao use impulso, movimento controlado.", video: "https://www.youtube.com/watch?v=taI4XduLpTk" },
  "pullover-halter": { nome: "Pullover com Halter", grupo: "Peito", series: "3x12", descricao: "Exercicio que trabalha peitoral e serrateis. Deitado transversalmente no banco.", comoExecutar: "Deite transversalmente no banco, segure um halter com as duas maos acima do peito, desca para tras ate sentir o alongamento e volte.", cuidados: "Mantenha o quadril elevado, movimento controlado.", video: "https://www.youtube.com/watch?v=s89BbdBQLhs" },
  "crossover-polia": { nome: "Crossover na Polia Alta", grupo: "Peito", series: "3x12", descricao: "Exercicio na polia para peitoral inferior e medio.", comoExecutar: "Fique entre as polias, puxe as alcas de cima para baixo e para dentro, cruzando levemente.", cuidados: "Tronco levemente inclinado, nao use peso excessivo.", video: "https://www.youtube.com/watch?v=taI4XduLpTk" },
  "flexao-bracos": { nome: "Flexao de Bracos", grupo: "Peito", series: "3x15", descricao: "Exercicio corporal para peitoral e triceps.", comoExecutar: "Posicao de prancha, desca o peito ate quase tocar o chao e empurre.", cuidados: "Mantenha o corpo reto, nao deixe o quadril cair.", video: "https://www.youtube.com/watch?v=IODxDxX7oi4" },

  // OMBRO
  "desenvolvimento-barra": { nome: "Desenvolvimento com Barra", grupo: "Ombro", series: "3x12", descricao: "Exercicio composto para deltoide anterior e medio.", comoExecutar: "Em pe ou sentado, segure a barra na altura dos ombros e empurre acima da cabeca.", cuidados: "Nao arqueie a lombar, controle a descida.", video: "https://www.youtube.com/watch?v=2yjwXTZQDDI" },
  "desenvolvimento-halteres": { nome: "Desenvolvimento com Halteres", grupo: "Ombro", series: "3x12", descricao: "Variacao com halteres para maior amplitude.", comoExecutar: "Sentado, segure halteres na linha dos ombros e empurre acima da cabeca.", cuidados: "Mantenha as costas apoiadas no banco.", video: "https://www.youtube.com/watch?v=qEwKCR5JCog" },
  "elevacao-lateral": { nome: "Elevacao Lateral", grupo: "Ombro", series: "3x12", descricao: "Isolamento do deltoide medio.", comoExecutar: "Em pe com halteres ao lado do corpo, eleve os bracos lateralmente ate a altura dos ombros.", cuidados: "Nao use impulso do corpo, cotovelos levemente flexionados.", video: "https://www.youtube.com/watch?v=3VcKaXpzqRo" },
  "elevacao-frontal": { nome: "Elevacao Frontal", grupo: "Ombro", series: "3x12", descricao: "Foco no deltoide anterior.", comoExecutar: "Em pe com halteres, eleve um braco de cada vez ou ambos a frente ate a altura dos ombros.", cuidados: "Nao balance o tronco, movimento controlado.", video: "https://www.youtube.com/watch?v=gzDXBWytcE0" },
  "remada-alta": { nome: "Remada Alta", grupo: "Ombro", series: "3x12", descricao: "Trabalha deltoide medio e trapezio.", comoExecutar: "Em pe com barra ou halteres, puxe ate a altura do queixo, cotovelos apontando para cima.", cuidados: "Nao suba acima da linha dos ombros se tiver problemas no ombro.", video: "https://www.youtube.com/watch?v=amCU-ziHITM" },
  "crucifixo-invertido": { nome: "Crucifixo Invertido", grupo: "Ombro", series: "3x12", descricao: "Foco no deltoide posterior.", comoExecutar: "Inclinado a frente com halteres, abra os bracos lateralmente para tras.", cuidados: "Mantenha as costas retas, contraia o deltoide posterior.", video: "https://www.youtube.com/watch?v=K3oRz-KnQGA" },
  "face-pull": { nome: "Face Pull", grupo: "Ombro", series: "3x15", descricao: "Fortalecimento do deltoide posterior e manguito rotador na polia.", comoExecutar: "Na polia alta com corda, puxe em direcao ao rosto abrindo os cotovelos.", cuidados: "Nao use peso pesado, foco na tecnica.", video: "https://www.youtube.com/watch?v=rep-qVOkmqg" },

  // TRICEPS
  "triceps-corda": { nome: "Triceps Corda na Polia", grupo: "Triceps", series: "3x15", descricao: "Exercicio de isolamento do triceps na polia.", comoExecutar: "Em pe de frente para a polia alta, empurre a corda para baixo estendendo os bracos.", cuidados: "Mantenha os cotovelos fixos ao lado do corpo.", video: "https://www.youtube.com/watch?v=vB5OHsJ3EME" },
  "triceps-barra-retar": { nome: "Triceps Barra Reta na Polia", grupo: "Triceps", series: "3x12", descricao: "Similar a corda mas com barra reta para mais carga.", comoExecutar: "Mesma posicao da corda, use barra reta e empurre para baixo.", cuidados: "Cotovelos fixos, nao balance o corpo.", video: "https://www.youtube.com/watch?v=2-LAMcpzVhg" },
  "triceps-frances": { nome: "Triceps Frances com Halter", grupo: "Triceps", series: "3x12", descricao: "Exercicio para cabeca longa do triceps.", comoExecutar: "Sentado ou em pe, segure um halter com as duas maos atras da cabeca e estenda os bracos.", cuidados: "Cotovelos apontando para cima, nao abra para os lados.", video: "https://www.youtube.com/watch?v=YbX7Wd8jQ-Q" },
  "triceps-testa": { nome: "Triceps Testa com Barra", grupo: "Triceps", series: "3x12", descricao: "Exercicio deitado para triceps.", comoExecutar: "Deite no banco, segure barra EZ, desca em direcao a testa e estenda.", cuidados: "Nao desca a barra na testa, controle o peso.", video: "https://www.youtube.com/watch?v=d_KZxkY_0cM" },
  "mergulho-paralelas": { nome: "Mergulho em Paralelas", grupo: "Triceps", series: "3x10", descricao: "Exercicio composto para triceps e peito.", comoExecutar: "Segure as barras paralelas, desca flexionando os bracos e suba.", cuidados: "Incline o corpo para frente para mais peito, reto para mais triceps.", video: "https://www.youtube.com/watch?v=2z8JmcrW-As" },
  "mergulho-banco": { nome: "Mergulho no Banco", grupo: "Triceps", series: "3x12", descricao: "Variacao mais simples do mergulho usando um banco.", comoExecutar: "Apoie as maos no banco atras do corpo, desca flexionando os cotovelos e suba.", cuidados: "Pies no chao ou em outro banco, nao desca demais.", video: "https://www.youtube.com/watch?v=0326dy_-CzM" },

  // COSTAS / DORSAL
  "puxada-frente-aberta": { nome: "Puxada Frontal Aberta", grupo: "Dorsal", series: "3x12", descricao: "Exercicio na polia alta para grande dorsal.", comoExecutar: "Sentado na maquina, puxe a barra ate a altura do peito com pegada aberta.", cuidados: "Nao puxe atrs do pescoco, incline levemente o tronco para trs.", video: "https://www.youtube.com/watch?v=CAwf7n6Luuc" },
  "puxada-frente-fechada": { nome: "Puxada Frontal Fechada (Triangulo)", grupo: "Dorsal", series: "3x12", descricao: "Puxada frontal com pegada fechada usando triangulo.", comoExecutar: "Sentado, puxe o triangulo da polia alta em direcao ao peito.", cuidados: "Puxe com as costas, nao com os bracos.", video: "https://www.youtube.com/watch?v=CAwf7n6Luuc" },
  "puxada-supinada": { nome: "Puxada Supinada", grupo: "Dorsal", series: "3x12", descricao: "Puxada com pegada supinada (palmas para cima), enfase no dorsal e bceps.", comoExecutar: "Sentado, segure a barra com pegada supinada e puxe ate o peito.", cuidados: "Controle o movimento, nao use impulso.", video: "https://www.youtube.com/watch?v=4t-R4OjYR0E" },
  "remada-bastra": { nome: "Remada Baixa na Polia", grupo: "Dorsal", series: "3x12", descricao: "Remada sentado na polia baixa para espessura das costas.", comoExecutar: "Sentado com ps no apoio, puxe o triangulo ou barra em direcao ao abdomen.", cuidados: "Costas retas, puxe com as escapulas.", video: "https://www.youtube.com/watch?v=GZbfZ033f74" },
  "remada-unilateral": { nome: "Remada Unilateral com Halter", grupo: "Dorsal", series: "3x12", descricao: "Remada com um braco apenas, apoio no banco.", comoExecutar: "Apoie um joelho e uma mo no banco, com a outra puxe o halter em direcao ao quadril.", cuidados: "Costas paralelas ao cho, puxe com o cotovelo.", video: "https://www.youtube.com/watch?v=pYcpY20QaE8" },
  "barra-fixa": { nome: "Barra Fixa", grupo: "Dorsal", series: "3x8", descricao: "Exercicio corporal para dorsal e bceps.", comoExecutar: "Pendurado na barra, puxe o corpo ate o queixo ultrapassar a barra.", cuidados: "Movimento completo, sem impulso.", video: "https://www.youtube.com/watch?v=eGo4IYlbE5g" },
  "remada-curvada": { nome: "Remada Curvada com Barra", grupo: "Dorsal", series: "3x12", descricao: "Remada com barra para espessura das costas.", comoExecutar: "Em pe com barra, incline o tronco para frente (~45 graus), puxe a barra ate o abdomen.", cuidados: "Costas retas, nao arqueie a lombar.", video: "https://www.youtube.com/watch?v=FWJR5Ve8bnQ" },

  // BICEPS
  "rosca-direta-barra": { nome: "Rosca Direta com Barra", grupo: "Biceps", series: "4x12", descricao: "Exercicio basico para bceps.", comoExecutar: "Em pe com barra, flexione os bracos trazendo a barra aos ombros.", cuidados: "Nao balance o corpo, cotovelos fixos ao lado.", video: "https://www.youtube.com/watch?v=kwG2ipFRgFo" },
  "rosca-direta-halteres": { nome: "Rosca Direta com Halteres", grupo: "Biceps", series: "3x12", descricao: "Rosca com halteres para maior amplitude.", comoExecutar: "Em pe com halteres, alterne ou faca ambos simultaneamente.", cuidados: "Controle a fase eccentrica.", video: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo" },
  "rosca-alternata": { nome: "Rosca Alternada com Halteres", grupo: "Biceps", series: "3x12", descricao: "Rosca alternando os bracos com halteres.", comoExecutar: "Sentado ou em pe, faca a rosca com um braco de cada vez.", cuidados: "Supine o pulso no topo para maior contracao.", video: "https://www.youtube.com/watch?v=soxrZlIlub0" },
  "rosca-martelo": { nome: "Rosca Martelo", grupo: "Biceps", series: "3x12", descricao: "Rosca com pegada neutra para braquiorradial e bceps.", comoExecutar: "Com halteres, palmas voltadas uma para a outra, suba sem girar o pulso.", cuidados: "Mantenha a pegada neutra durante todo o movimento.", video: "https://www.youtube.com/watch?v=zC3nLlEvin4" },
  "rosca-scott": { nome: "Rosca Scott (Banco Scott)", grupo: "Biceps", series: "4x12", descricao: "Rosca no banco Scott para isolamento do bceps.", comoExecutar: "Sente no banco Scott, apoio os trceps na almofada e faca a rosca com barra EZ ou halteres.", cuidados: "Nao estenda completamente no fundo, mantenha tenso.", video: "https://www.youtube.com/watch?v=fIWP-FRFNU0" },
  "rosca-concentrada": { nome: "Rosca Concentrada", grupo: "Biceps", series: "3x10", descricao: "Rosca sentado com apoio na coxa.", comoExecutar: "Sentado, apoio o cotovelo na parte interna da coxa e faca a rosca com halter.", cuidados: "Movimento lento e controlado.", video: "https://www.youtube.com/watch?v=0AUGkch3tzc" },

  // PERNAS - QUADRICEPS
  "leg-press-45": { nome: "Leg Press 45", grupo: "Perna", series: "3x15", descricao: "Exercicio composto para quadriceps em maquina inclinada.", comoExecutar: "Sente na maquina, ps na plataforma na largura dos ombros, desca a plataforma e empurre.", cuidados: "Nao trave os joelhos no topo, desca com controle.", video: "https://www.youtube.com/watch?v=IZxyjW7MPJQ" },
  "extensora": { nome: "Cadeira Extensora", grupo: "Perna", series: "3x15", descricao: "Isolamento do quadriceps.", comoExecutar: "Sentado na maquina, estenda as pernas ate ficarem retas e desca com controle.", cuidados: "Nao use impulso, segure 1 segundo no topo.", video: "https://www.youtube.com/watch?v=YyvSfVjQeL0" },
  "agachamento-livre": { nome: "Agachamento Livre com Barra", grupo: "Perna", series: "4x10", descricao: "Rei dos exercicios de perna - quadriceps, gluteos e posterior.", comoExecutar: "Barra nas costas, ps largura dos ombros, desca como se fosse sentar e suba.", cuidados: "Joelhos na direcao dos ps, costas retas, nao deixe o joelho entrar para dentro.", video: "https://www.youtube.com/watch?v=ultWZbUMPL8" },
  "hack-squat": { nome: "Hack Squat", grupo: "Perna", series: "3x15", descricao: "Agachamento na maquina hack para quadriceps.", comoExecutar: "Na maquina, ombros apoiados, desca com controle e empurre a plataforma.", cuidados: "Pies na posicao media, nao trave os joelhos.", video: "https://www.youtube.com/watch?v=ZMqVqGVuOzU" },
  "agachamento-sumo": { nome: "Agachamento Sumo com Halter", grupo: "Perna", series: "3x15", descricao: "Variacao com base larga para adutores e quadriceps.", comoExecutar: "Ps muito afastados, pontas para fora, segure halter na frente e faca o agachamento.", cuidados: "Mantenha os joelhos na direcao dos ps.", video: "https://www.youtube.com/watch?v=K31JxjHmIiA" },
  "afundo": { nome: "Afundo com Halteres", grupo: "Perna", series: "3x12", descricao: "Exercicio unilateral para quadriceps e gluteos.", comoExecutar: "Em pe com halteres, de um passo a frente e desca ate os dois joelhos a 90 graus.", cuidados: "Joelho da frente nao ultrapassar a ponta do p.", video: "https://www.youtube.com/watch?v=D7KaJc4QeEY" },

  // PERNAS - POSTERIOR
  "flexora-deitada": { nome: "Mesa Flexora", grupo: "Perna", series: "3x15", descricao: "Isolamento dos isquiotibiais (posterior de coxa).", comoExecutar: "Deitado de bruco, flexione as pernas trazendo os calcanhares aos gluteos.", cuidados: "Quadril preso no banco, movimento controlado.", video: "https://www.youtube.com/watch?v=1Tq3QdYUJHs" },
  "flexora-sentada": { nome: "Cadeira Flexora", grupo: "Perna", series: "3x12", descricao: "Flexora na posicao sentada.", comoExecutar: "Sentado, flexione as pernas vencendo a resistencia.", cuidados: "Mantenha as costas apoiadas.", video: "https://www.youtube.com/watch?v=1Tq3QdYUJHs" },
  "stiff": { nome: "Stiff com Barra", grupo: "Perna", series: "3x12", descricao: "Exercicio para posterior de coxa e gluteos.", comoExecutar: "Em pe com barra, desca a barra rente s pernas com joelhos semi-estendidos e suba.", cuidados: "Costas sempre retas, nao arredonde a lombar.", video: "https://www.youtube.com/watch?v=JCXUYuzwNrM" },
  "elevacao-pelve": { nome: "Elevao Plvica", grupo: "Perna", series: "3x12", descricao: "Exercicio para gluteos.", comoExecutar: "Deitado de costas, joelhos flexionados, eleve o quadril contraindo os gluteos.", cuidados: "Contraia os gluteos no topo, nao hiperestenda a lombar.", video: "https://www.youtube.com/watch?v=OUgsJ8-Vi0E" },

  // PANTURRILHA
  "panturrilha-em-pe": { nome: "Panturrilha em P na Maquina", grupo: "Perna", series: "4x20", descricao: "Exercicio para gastrocnmio (panturrilha).", comoExecutar: "Em p na maquina, suba na ponta dos ps e desca ate o alongamento completo.", cuidados: "Amplitude mxima, segure 1-2s no topo.", video: "https://www.youtube.com/watch?v=gwLzBJYoWlI" },
  "panturrilha-sentado": { nome: "Panturrilha Sentado", grupo: "Perna", series: "4x15", descricao: "Foco no sleo (porco mais profundo da panturrilha).", comoExecutar: "Sentado na maquina com apoio nos joelhos, suba na ponta dos ps.", cuidados: "Mesma amplitude, controle a descida.", video: "https://www.youtube.com/watch?v=JbyHn9mHkOY" },

  // ABDOMEN
  "abdominal-crunch": { nome: "Abdominal Crunch", grupo: "Abdomen", series: "3x20", descricao: "Exercicio basico para reto abdominal.", comoExecutar: "Deitado, joelhos flexionados, eleve os ombros do chao contraindo o abdmen.", cuidados: "Nao puxe o pescoco, foco na contraco abdominal.", video: "https://www.youtube.com/watch?v=Xyd_fa5zoEU" },
  "abdominal-infra": { nome: "Abdominal Infra", grupo: "Abdomen", series: "3x15", descricao: "Foco na regio inferior do abdmen.", comoExecutar: "Deitado de costas, eleve as pernas retas ou joelhos em direcao ao peito.", cuidados: "Controle a descida, nao balance as pernas.", video: "https://www.youtube.com/watch?v=1f8yoEzxKkI" },
  "abdominal-obliquo": { nome: "Abdominal Oblquo", grupo: "Abdomen", series: "3x20", descricao: "Trabalha os oblquos laterais.", comoExecutar: "Deitado, eleve o tronco em direcao ao joelho oposto.", cuidados: "Rotao controlada.", video: "https://www.youtube.com/watch?v=1f8yoEzxKkI" },
  "prancha": { nome: "Prancha Isomtrica", grupo: "Abdomen", series: "3x45s", descricao: "Exercicio isomtrico para core.", comoExecutar: "Apoie os antebraos e pontas dos ps no cho, corpo reto.", cuidados: "Nao deixe o quadril cair ou subir demais.", video: "https://www.youtube.com/watch?v=ASdvN_XEl_c" },
  "russian-twist": { nome: "Russian Twist", grupo: "Abdomen", series: "3x20", descricao: "Rotao do tronco para oblquos.", comoExecutar: "Sentado com ps elevados, gire o tronco de um lado para o outro.", cuidados: "Costas retas, movimento controlado.", video: "https://www.youtube.com/watch?v=wkD8rjkodUI" },

  // TRAPEZIO
  "encolhimento-halteres": { nome: "Encolhimento com Halteres", grupo: "Trapzio", series: "3x15", descricao: "Isolamento do trapezio superior.", comoExecutar: "Em pe com halteres, eleve os ombros em direcao s orelhas e desca.", cuidados: "Nao gire os ombros, suba e desca reto.", video: "https://www.youtube.com/watch?v=cJRVVxmytaM" },
};
